### PR TITLE
Fix broken tests

### PR DESCRIPTION
**Pull request by cbaines**

### CODE REVIEW

**Comment by cbaines** [comment]
I think this does fix test issues, but there looks to be an existing issue with the Dockerfile that is causing the CI build to fail... :rage:

**Comment by cbaines** [comment]
@thomasleese I'm seeing
```
[docker] [91mE: Unable to locate package default-libmysqlclient-dev
```
in https://ci.integration.publishing.service.gov.uk/job/release/job/fix-broken-tests/1/console .

Any idea why what weird stuff is going on in the Dockertfile? That obviously was working for https://github.com/alphagov/release/pull/215/commits/6c7d2b2e23ef587868971e63f48ed5618a8953c4 to be merged in?

**Comment by thomasleese** [comment]
@cbaines I'm not really sure what's going on there.

We had to change the package because the Ruby 2.5 Docker base image uses a more recent version of Debian (Stretch, rather than Jessie) and we found that the old `mysql-server` package was no longer available and instead we had to use `default-mysql-server` because in Stretch, the default MySQL implementation has been changed to MariaDB rather than MySQL itself.

We found articles online (although I must admit I'm struggling to find them again now) that suggested using the new `default-mysql-server` package which depends on `mariadb-server`.

**Comment by cbaines** [comment]
> @cbaines I'm not really sure what's going on there.

I rolled the Docker :game_die: again, and it didn't break :man_shrugging: .

Thanks for the information anyway :)

**Pull request merged**
